### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by KreAch3R** [andi38/TPMS#2]
Hello, 

do you think BLE 5.0 sensors like this: https://www.aliexpress.com/item/32823818142.html?spm=a2g0o.cart.0.0.28d238dah0sglj&mp=1 also use the same broadcast pattern and your script could work. or is it specific to the PECHAM sensors you have posted?

**Comment by andi38** [comment]
Unfortunately I don't know about the EKETOOL sensors.

**Comment by KreAch3R** [comment]
Ok, thank you for the reply. 

In your experience, would you guess that they use the same pattern or will it be a complete different? Is there something completely custom in the broadcast pattern you reverse engineered?

**Comment by KreAch3R** [comment]
@andi38 Hello again,

This time I have good news. Thanks to your script here, I managed to capture and show the PECHAM TPMS information on my OpenAuto setup. Check the code here: https://github.com/KreAch3R/tpms-oap

https://bluewavestudio.io/community/thread-3874-post-20051.html

**Comment by VincentMasselis** [comment]
I was in my way to give you some tip for the Sysgration sensors but I think you already found how to manage it when I take a look at the Acknowledgement chapter in your repo :D

**Comment by KreAch3R** [comment]
Yes @VincentMasselis , I found your great app and incorporated your byte logic into my script!

It's working great, thank you very much!

So just to make it clear, my scripts supports both PECHAM and SYSGRATION/EKETOOL sensors thanks to you guys. :)

**Comment by VincentMasselis** [comment]
I'm also currently working on PECHAM integration, I've found this issue while googling ;)
