### ISSUE TITLE
Pressure traduction problem

### ISSUE THREAD

**Issue by PierFee** [andi38/TPMS#4]
Hi, I need some help on the traduction of the string I receive from the sensors.
4031200146150126
3631201122151143

These are two of the many strings I receive from the tpms sensors and I think the correct division is this: 36 31 20 1 122 151 143
31 is the voltage: 3.1V
20 is the correct temperature in celsius degrees
but the pressure is 1122 or 1 122 but calculating it I found 120 Psi instead of 25 psi.

Should you be more specific on the traduction method?
Thank you.

**Comment by andi38** [comment]
Might the difference be explained by absolute vs. relative pressure? Abs. vs. rel. is 14.5 psi or 145 (1/10 psi) difference.

**Comment by PierFee** [comment]
Absolute pressure is the gauge pressure + atmospheric pressure.
So if 122 is my absolute pressure (1/10) I have to subtract 14.5psi -> 145 (1/10) = -2,3psi impossible
